import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import axios from "axios";
import { useState, useEffect } from "react";
import { prisma } from "../lib/prisma";

export async function getServerSideProps() {
  const fruits = await prisma.fruits.findMany();

  return {
    props: {
      fruits: JSON.parse(JSON.stringify(fruits)),
    },
  };
}
type Props = {
  fruits: { name: string; description: string }[];
};
const Home: NextPage<Props> = ({ fruits = [] }) => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="text-3xl font-bold underline">
        {fruits.map((f, i) => (
          <div key={i}>
            <label>name</label>
            <p>{f.name}</p>
            <label>descricao</label>
            <p>{f.description}</p>
          </div>
        ))}
      </main>
    </div>
  );
};

export default Home;
